// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.hamcrest.MatcherAssert;
import org.junit.After;
import static org.hamcrest.CoreMatchers.is;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.JavascriptExecutor;

import java.time.Duration;
import java.util.*;
public class PLOA2024Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pLOA2024() {
    // Abrir site
    driver.get("http://10.2.1.110:8080/legislativo-proposta-emenda-loa/2024/gabinete");
    driver.findElement(By.id("kc-form-login")).click();
    driver.findElement(By.id("username")).click();
    driver.findElement(By.id("username")).sendKeys("usuario");
    driver.findElement(By.id("password")).sendKeys("usuario");
    driver.findElement(By.id("kc-login")).click();
    // Abrir legislativo
    driver.findElement(By.id("legislativo-menu")).click();
    // Abrir menu PLOA 2024
    driver.findElement(By.cssSelector("#submenuEmendasLOA5Item .svg-inline--fa")).click();
    // Afirmar que menu de PLOA 2024 existe
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#submenuEmendasLOA5Collapse li:nth-child(1)"));
      assert(elements.size() > 0);
    }
    MatcherAssert.assertThat(driver.findElement(By.cssSelector("#submenuEmendasLOA5Collapse li:nth-child(1) span")).getText(), is("Propostas de Emenda"));
    MatcherAssert.assertThat(driver.findElement(By.cssSelector("div > li:nth-child(2) span")).getText(), is("Transferências Especiais"));
  }
}