// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class PLOA2024Test {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void pLOA2024() {
    // Abrir site
    driver.get("http://10.2.1.110:8080/legislativo-proposta-emenda-loa/2024/gabinete");
    // Abrir legislativo
    driver.findElement(By.id("legislativo-menu")).click();
    // Abrir menu PLOA 2024
    driver.findElement(By.cssSelector("#submenuEmendasLOA5Item .svg-inline--fa")).click();
    // Afirmar que menu de PLOA 2024 existe
    {
      List<WebElement> elements = driver.findElements(By.cssSelector("#submenuEmendasLOA5Collapse li:nth-child(1)"));
      assert(elements.size() > 0);
    }
    assertThat(driver.findElement(By.cssSelector("#submenuEmendasLOA5Collapse li:nth-child(1) span")).getText(), is("Propostas de Emenda"));
    assertThat(driver.findElement(By.cssSelector("div > li:nth-child(2) span")).getText(), is("Transferências Especiais"));
  }
}
