// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class SalvarRascunhoTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void salvarRascunho() {
    // Abrir site
    driver.get("http://10.2.1.110:8080/legislativo-proposta-emenda-loa/2024/EMENDA/new");
    // Verificar botões
    {
      List<WebElement> elements = driver.findElements(By.xpath("//*[@id=\"save-draft\"]"));
      assert(elements.size() > 0);
    }
    // Preenchendo opções genéricas
    driver.findElement(By.id("field_deputado")).click();
    {
      WebElement dropdown = driver.findElement(By.id("field_deputado"));
      dropdown.findElement(By.xpath("//option[. = 'Dep. Joaquim Nabuco']")).click();
    }
    driver.findElement(By.xpath("//ng-select/div/div")).click();
    driver.findElement(By.xpath("//div/div[2]/div")).click();
    driver.findElement(By.xpath("//div[2]/input")).click();
    driver.findElement(By.xpath("//div/div[2]/div/div")).click();
    driver.findElement(By.xpath("//div[2]/input")).click();
    driver.findElement(By.xpath("//div[2]/div[2]/div")).click();
    driver.findElement(By.xpath("//div[2]/input")).click();
    driver.findElement(By.xpath("//div/div[2]/div/div")).click();
    js.executeScript("window.scrollTo(0,500)");
    driver.findElement(By.xpath("//div[2]/input")).click();
    driver.findElement(By.xpath("//div/div[2]/div/div")).click();
    driver.findElement(By.id("field_objetivo")).sendKeys("gftrgf");
    driver.findElement(By.id("field_valor")).sendKeys("60001");
    // Clicar Salvar Rascunho
    driver.findElement(By.xpath("//*[@id=\"save-draft\"]")).click();
  }
}
