// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.JavascriptExecutor;
import java.util.*;
public class TodasasPropdeEmendaTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void todasasPropdeEmenda() {
    // Abrir site
    driver.get("http://10.2.1.110:8080/legislativo-proposta-emenda-loa/2024/EMENDA/new");
    // Expandir menu
    driver.findElement(By.cssSelector("#legislativo-menu > span > span")).click();
    driver.findElement(By.id("submenuEmendasLOA5Item")).click();
    // Clicar em Propostas de Emenda
    driver.findElement(By.cssSelector("#submenuEmendasLOA5Collapse li:nth-child(1) span")).click();
  }
}